# Server
server.port=8080
spring.application.name=etudiant-service

# Database
spring.datasource.url=jdbc:postgresql://db:5432/etudiantdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Logs
logging.level.org.springframework=INFO

